export interface Chain {
  name: string;
  url: string;
}

export const CHAINS: Record<string, Chain[]> = {
  pet:          [{ name: "PetPro", url: "https://www.petpro.co.id" }, { name: "Hypermart", url: "https://www.hypermart.co.id" }, { name: "Carrefour Indonesia", url: "https://www.carrefour.co.id" }, { name: "Indomaret", url: "https://www.indomaret.co.id" }],
  pharmacy:     [{ name: "Kimia Farma", url: "https://www.kimiafarma.co.id" }, { name: "Guardian", url: "https://www.guardian.co.id" }, { name: "Century Health", url: "https://www.centuryhealthcare.me" }, { name: "K-24", url: "https://www.k-24.co.id" }, { name: "Watson", url: "https://www.watson.co.id" }],
  electronics:  [{ name: "Erafone", url: "https://www.erafone.com" }, { name: "iBox", url: "https://www.ibox.co.id" }, { name: "Electronic City", url: "https://www.electroniccity.co.id" }, { name: "Hartono Elektronik", url: "https://www.hartono.co.id" }, { name: "Samsung Store", url: "https://www.samsung.com/id" }],
  mobile:       [{ name: "iBox", url: "https://www.ibox.co.id" }, { name: "Erafone", url: "https://www.erafone.com" }, { name: "OPPO Store", url: "https://www.oppo.com/id" }, { name: "Samsung Store", url: "https://www.samsung.com/id" }, { name: "Vivo Store", url: "https://www.vivo.com/id" }],
  computer:     [{ name: "iBox", url: "https://www.ibox.co.id" }, { name: "Erafone", url: "https://www.erafone.com" }, { name: "Electronic City", url: "https://www.electroniccity.co.id" }, { name: "Hartono Elektronik", url: "https://www.hartono.co.id" }],
  fashion:      [{ name: "Matahari Department Store", url: "https://www.matahari.co.id" }, { name: "Ramayana", url: "https://www.ramayana.co.id" }, { name: "H&M Indonesia", url: "https://www.hm.com/id" }, { name: "Zara Indonesia", url: "https://www.zara.com/id" }, { name: "Cotton On", url: "https://cottonon.com/ID" }],
  shoes:        [{ name: "Sports Station", url: "https://www.sportsstation.co.id" }, { name: "Planet Sports", url: "https://www.planetsports.co.id" }, { name: "Matahari Department Store", url: "https://www.matahari.co.id" }, { name: "Payless ShoeSource", url: "https://www.payless.co.id" }],
  sports:       [{ name: "Decathlon", url: "https://www.decathlon.co.id" }, { name: "Sports Station", url: "https://www.sportsstation.co.id" }, { name: "Planet Sports", url: "https://www.planetsports.co.id" }, { name: "Intersport", url: "https://www.intersport.co.id" }],
  baby:         [{ name: "Mothercare", url: "https://www.mothercare.co.id" }, { name: "Baby Barn", url: "https://www.babybarn.id" }, { name: "Kidz Station", url: "https://www.kidzstation.co.id" }, { name: "Indomaret", url: "https://www.indomaret.co.id" }],
  toys:         [{ name: "Toys\"R\"Us Indonesia", url: "https://www.toysrus.co.id" }, { name: "Kidz Station", url: "https://www.kidzstation.co.id" }, { name: "Matahari Department Store", url: "https://www.matahari.co.id" }, { name: "Carrefour Indonesia", url: "https://www.carrefour.co.id" }],
  books:        [{ name: "Gramedia", url: "https://www.gramedia.com" }, { name: "Periplus", url: "https://www.periplus.com" }, { name: "Togamas", url: "https://www.togamas.com" }, { name: "Popular Bookstore", url: "https://www.popular.co.id" }],
  hardware:     [{ name: "ACE Hardware", url: "https://www.acehardware.co.id" }, { name: "Kawan Lama", url: "https://www.kawanlama.com" }, { name: "Mitra10", url: "https://www.mitra10.com" }, { name: "Depo Bangunan", url: "https://www.depobangunan.com" }],
  beauty:       [{ name: "Guardian", url: "https://www.guardian.co.id" }, { name: "Watson", url: "https://www.watson.co.id" }, { name: "Sociolla", url: "https://www.sociolla.com" }, { name: "Sephora Indonesia", url: "https://www.sephora.co.id" }, { name: "The Body Shop", url: "https://www.thebodyshop.co.id" }],
  music:        [{ name: "Duta Suara", url: "https://www.dutasuara.co.id" }, { name: "Bentoel Musik", url: "https://www.bentoelmusik.com" }, { name: "Melodia", url: "https://www.melodia.co.id" }, { name: "Raja Musik", url: "https://www.rajamusik.com" }],
  garden:       [{ name: "ACE Hardware", url: "https://www.acehardware.co.id" }, { name: "Carrefour Indonesia", url: "https://www.carrefour.co.id" }, { name: "Hypermart", url: "https://www.hypermart.co.id" }],
  automotive:   [{ name: "Ottoparts", url: "https://www.ottoparts.com" }, { name: "Motopart", url: "https://www.motopart.co.id" }, { name: "Auto2000", url: "https://www.auto2000.co.id" }, { name: "Bengkel Ahass (Honda)", url: "https://www.astra-honda.com/ahass" }, { name: "Yamaha Dealer Resmi", url: "https://www.yamaha-motor.co.id" }],
  grocery:      [{ name: "Indomaret", url: "https://www.indomaret.co.id" }, { name: "Alfamart", url: "https://www.alfamart.co.id" }, { name: "Hypermart", url: "https://www.hypermart.co.id" }, { name: "Superindo", url: "https://www.superindo.co.id" }, { name: "Ranch Market", url: "https://www.ranchmarket.co.id" }],
  food_specialty:[{ name: "Ranch Market", url: "https://www.ranchmarket.co.id" }, { name: "Grand Lucky", url: "https://www.grandlucky.com" }, { name: "Kemchicks", url: "https://www.kemchicks.com" }, { name: "Total Buah Segar", url: "https://www.totalbuahsegar.com" }],
  general:      [{ name: "Hypermart", url: "https://www.hypermart.co.id" }, { name: "Carrefour Indonesia", url: "https://www.carrefour.co.id" }, { name: "Matahari Department Store", url: "https://www.matahari.co.id" }, { name: "Indomaret", url: "https://www.indomaret.co.id" }, { name: "ACE Hardware", url: "https://www.acehardware.co.id" }],
};

export const STREET_PREFIXES = [
  "Jl. Sudirman", "Jl. Gatot Subroto", "Jl. Thamrin", "Jl. Rasuna Said",
  "Jl. Hayam Wuruk", "Jl. Gajah Mada", "Jl. Gunung Sahari", "Jl. Mangga Dua Raya",
  "Jl. Boulevard", "Jl. Asia Afrika", "Jl. Pemuda", "Jl. Diponegoro",
  "Jl. Ahmad Yani", "Jl. Pahlawan", "Jl. Raya Darmo",
];

export const VARIANT_HINTS: Record<string, string[]> = {
  pet:         ["— 2kg bag", "— 500g pack", "— 4kg bag", "— 1.5kg bag", "— 3kg bag", "— multi-pack"],
  pharmacy:    ["— 30 tablets", "— 60 capsules", "— 100ml bottle", "— 10 strips", "— 200mg", "— 500mg"],
  electronics: ["— latest model", "— bundle pack", "— with warranty", "— official store", "— new arrival"],
  mobile:      ["— 128GB", "— 256GB", "— 8/128GB", "— 12/256GB", "— with case"],
  computer:    ["— retail box", "— OEM pack", "— with accessories", "— bundle", "— official"],
  fashion:     ["— size S-XL", "— new collection", "— limited stock", "— bestseller"],
  shoes:       ["— size 38-44", "— new arrival", "— limited edition", "— official"],
  sports:      ["— beginner", "— intermediate", "— professional", "— with bag", "— complete set"],
  baby:        ["— newborn pack", "— 0-6 months", "— 6-12 months", "— economy pack", "— jumbo pack"],
  toys:        ["— new sealed", "— gift box", "— collector edition", "— complete set"],
  books:       ["— softcover", "— hardcover", "— latest edition", "— bestseller"],
  hardware:    ["— professional grade", "— DIY set", "— complete kit", "— with accessories"],
  beauty:      ["— 50ml", "— travel size", "— full size", "— set"],
  grocery:     ["— 1kg", "— 500g", "— bulk pack", "— premium grade"],
  food_specialty: ["— 250g", "— 100g", "— premium", "— organic"],
  automotive:  ["— OEM spec", "— aftermarket", "— genuine part", "— set of 2"],
  music:       ["— with case", "— bundle", "— starter pack", "— professional"],
  garden:      ["— with pot", "— live plant", "— seedling", "— mature plant"],
  general:     ["", "— available in-store", "— in stock", "— ask staff"],
};

export const MODEL_NAMES: Array<{ pattern: RegExp; models: string[] }> = [
  { pattern: /dyson.*v15|v15.*dyson/, models: ["Dyson V15 Detect Absolute", "Dyson V15 Detect Origin", "Dyson V15s Detect Submarine"] },
  { pattern: /dyson.*v11|v11.*dyson/, models: ["Dyson V11 Absolute", "Dyson V11 Animal", "Dyson V11 Torque Drive"] },
  { pattern: /dyson.*v8|v8.*dyson/, models: ["Dyson V8 Origin", "Dyson V8 Animal", "Dyson V8 Absolute"] },
  { pattern: /dyson.*v10|v10.*dyson/, models: ["Dyson V10 Animal", "Dyson V10 Motorhead", "Dyson Cyclone V10 Absolute"] },
  { pattern: /dyson|vacuum.*clean|vacum|vacume/, models: ["Dyson V11 Absolute Cordless", "Dyson V8 Origin Cordless", "Dyson V10 Animal Cordless", "Dyson Ball Animal 2", "Dyson Cyclone V10 Motorhead"] },
  { pattern: /yonex.*badminton|badminton.*yonex|yonex.*raket/, models: ["Yonex Arcsaber 11 Pro", "Yonex Nanoflare 700", "Yonex Astrox 88S Pro", "Yonex Voltric Z Force II", "Yonex Duora 10"] },
  { pattern: /victor.*badminton|badminton.*victor/, models: ["Victor Thruster K 9900", "Victor Jetspeed S 12", "Victor Brave Sword 12SE", "Victor Auraspeed 90S"] },
  { pattern: /badminton|raket/, models: ["Yonex Arcsaber 7 Pro", "Victor Auraspeed 70K", "Li-Ning Aeronaut 9000", "Babolat Satelite Gravity 74"] },
  { pattern: /matcha.*ceremonial|ceremonial.*matcha/, models: ["Ippodo Kan-no-shiro Matcha 40g", "Marukyu Koyamaen Unkaku 20g", "Aiya Ceremonial Matcha 30g"] },
  { pattern: /matcha/, models: ["Matchaful Organic Matcha 50g", "Aiya Cooking Grade Matcha 100g", "Ippodo Matcha Powder 100g", "Ceremonial Grade Matcha 30g", "Midori Spring Matcha 250g"] },
  { pattern: /royal canin.*cat|cat.*royal canin/, models: ["Royal Canin Indoor Adult 4kg", "Royal Canin Sterilised 2kg", "Royal Canin Kitten 2kg", "Royal Canin Indoor 7+ 1.5kg"] },
  { pattern: /royal canin.*dog|dog.*royal canin/, models: ["Royal Canin Medium Adult 4kg", "Royal Canin Maxi Adult 4kg", "Royal Canin Mini Adult 2kg"] },
  { pattern: /royal canin/, models: ["Royal Canin Indoor Adult 4kg", "Royal Canin Fit 32 2kg", "Royal Canin Kitten 2kg", "Royal Canin Sterilised 2kg"] },
  { pattern: /whiskas/, models: ["Whiskas Tuna Adult 1.2kg", "Whiskas Salmon Pouch 85g", "Whiskas Mackerel Adult 1.2kg", "Whiskas Kitten Milk 85g"] },
  { pattern: /vitamin.*c|c.*vitamin/, models: ["Nature's Plus Vitamin C 1000mg 60 tabs", "Ester-C 500mg 60 caps", "Vitamin C 1000mg Effervescent 20 tabs", "Blackmores Vitamin C 1000mg 60 tabs"] },
  { pattern: /vitamin|suplemen|supplement/, models: ["Blackmores Daily C 500mg 60 tabs", "Nature's Plus Multi Vitamin 60 caps", "Herbalife Formula 1 Chocolate 550g", "Nutrifactor Vitamin D3 1000IU 60 caps"] },
  { pattern: /iphone.*15|15.*iphone/, models: ["Apple iPhone 15 128GB Black", "Apple iPhone 15 256GB Blue", "Apple iPhone 15 Plus 128GB", "Apple iPhone 15 Pro 256GB Natural Titanium"] },
  { pattern: /iphone.*14|14.*iphone/, models: ["Apple iPhone 14 128GB Midnight", "Apple iPhone 14 256GB Starlight", "Apple iPhone 14 Plus 128GB"] },
  { pattern: /iphone/, models: ["Apple iPhone 15 128GB Black", "Apple iPhone 14 128GB Midnight", "Apple iPhone 13 128GB Green", "Apple iPhone SE 64GB Black"] },
  { pattern: /samsung.*s24|s24.*samsung/, models: ["Samsung Galaxy S24 256GB Onyx Black", "Samsung Galaxy S24+ 256GB Cobalt Violet", "Samsung Galaxy S24 Ultra 512GB Titanium Black"] },
  { pattern: /samsung/, models: ["Samsung Galaxy A55 5G 256GB Blue", "Samsung Galaxy S24 256GB", "Samsung Galaxy A35 5G 128GB", "Samsung Galaxy Tab A9+ 64GB"] },
  { pattern: /macbook.*pro/, models: ["Apple MacBook Pro 14\" M3 Pro 512GB", "Apple MacBook Pro 16\" M3 Max 1TB", "Apple MacBook Pro 13\" M2 256GB"] },
  { pattern: /macbook.*air/, models: ["Apple MacBook Air 13\" M3 256GB Midnight", "Apple MacBook Air 15\" M3 512GB Starlight"] },
  { pattern: /macbook/, models: ["Apple MacBook Air 13\" M3 256GB", "Apple MacBook Pro 14\" M3 Pro 512GB", "Apple MacBook Air 15\" M2 256GB"] },
  { pattern: /yamaha.*gitar|gitar.*yamaha|yamaha.*guitar|guitar.*yamaha/, models: ["Yamaha FG800 Acoustic Guitar", "Yamaha F310 Acoustic Guitar", "Yamaha APXT2 3/4 Acoustic-Electric", "Yamaha C40 Classical Guitar"] },
  { pattern: /gitar|guitar/, models: ["Yamaha FG800 Acoustic Guitar", "Fender CD-60S Acoustic Guitar", "Cort AF510 Acoustic Guitar", "Epiphone DR-100 Acoustic Guitar"] },
  { pattern: /lego.*technic/, models: ["LEGO Technic McLaren F1 42141", "LEGO Technic Bugatti Bolide 42151", "LEGO Technic Land Rover Defender 42110"] },
  { pattern: /lego.*city/, models: ["LEGO City Police Station 60316", "LEGO City Fire Station 60320", "LEGO City Hospital 60330"] },
  { pattern: /lego/, models: ["LEGO Creator 3-in-1 Beach House 31138", "LEGO City Police Car 60312", "LEGO Technic 4×4 Off-Roader 42139", "LEGO Classic Bricks Set 11013"] },
  { pattern: /rtx.*4090/, models: ["ASUS ROG Strix GeForce RTX 4090 24GB", "MSI GeForce RTX 4090 GAMING X TRIO 24GB"] },
  { pattern: /rtx.*4080/, models: ["ASUS TUF Gaming GeForce RTX 4080 16GB", "Gigabyte GeForce RTX 4080 GAMING OC 16GB"] },
  { pattern: /rtx.*4070/, models: ["MSI GeForce RTX 4070 GAMING X TRIO 12GB", "ASUS Dual GeForce RTX 4070 OC 12GB", "Gigabyte GeForce RTX 4070 WINDFORCE 3X 12GB"] },
  { pattern: /rtx.*3080/, models: ["ASUS ROG Strix GeForce RTX 3080 10GB", "Gigabyte RTX 3080 GAMING OC 10GB"] },
  { pattern: /rtx|gtx|\bgpu\b|graphics card/, models: ["ASUS Dual GeForce RTX 4070 OC 12GB", "MSI GeForce RTX 4060 GAMING X 8GB", "Gigabyte RTX 3060 GAMING OC 12GB", "Sapphire Radeon RX 7600 8GB"] },
  { pattern: /dyson.*airwrap|airwrap/, models: ["Dyson Airwrap Multi-Styler Complete Long", "Dyson Airwrap HS05 Complete", "Dyson Corrale Straightener"] },
  { pattern: /dyson.*hair|hair.*dyson|dyson.*supersonic|supersonic/, models: ["Dyson Supersonic Hair Dryer HD08", "Dyson Supersonic HD03 Gift Edition", "Dyson Airwrap Multi-Styler HS05"] },
];
